name: tebak_gambar_nusantara
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  http: ^0.13.3
  shared_preferences: ^2.2.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets: 
  - assets/
  - assets/menu-background.jpeg
  - assets/icon1-wow.png
  - assets/icon2-wow.png
  - assets/icon3-wow.png
  - assets/background.png
  - assets/Prambanan.jpeg
  - assets/BULB.png
  fonts:
    - family: Galindo
      fonts:
        - asset: fonts/Galindo-Regular.ttf



